amisitefinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePageView.as_view(), name='home'),
    path('workorder/', include('wordorderapp.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wordorderapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'wordorderapp'

urlpatterns = [
    path('', views.HomePage1View.as_view(), name='home1'),
    path('workorder/', views.IndexView.as_view(), name='index'),
    path('workorder/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('workorderinvoicesent/', views.IndexView1.as_view(), name='index1'),
    path('workordertotallist/', views.IndexView2.as_view(), name='index2'),
    path('workordercreate/', views.WorkCreate.as_view(), name='creatework'),
    path('workorderupdate/<int:pk>/', views.WorkUpdate.as_view(), name='updatework'),
    path('workorderupdate1/<int:pk>/', views.WorkUpdate1.as_view(), name='updatework1'),
    path('workorderupdateadmin/<int:pk>/', views.WorkUpdateAdmin.as_view, name='updateworkadmin'),
    path('workorderdelete/', views.WorkDelete.as_view(), name='workorderdelete'),
    path('dailyjournal/', views.DailyCreate.as_view(), name='daily'),
    path('register/', views.UserFormView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('search/', views.WorkOrderSearchView.as_view(), name='search'),
    path('logoutsuccess/', views.LogoutSuccessView.as_view(), name='logoutsuccess'),
    path('loginsuccess/', views.LoginSuccessView.as_view(), name='loginsuccess')

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wordorderapp/models.py
from django.db import models
import datetime
from django.urls import reverse
from django.conf import settings

class Workorder(models.Model):
    addressnumber = models.DecimalField(max_digits=10, decimal_places=0)
    addressstreet = models.CharField(max_length=60)
    addresstown = models.CharField(max_length=60)
    addressstate = models.CharField(max_length=60)
    quickdescrip = models.CharField(max_length=350)
    lockboxcode = models.CharField(max_length=25)
    description = models.CharField(max_length=300)
    proposalorestimatenumber = models.DecimalField(max_digits=15, decimal_places=0)
    clientemailinfo = models.CharField(max_length=400)
    techniciancompletionnotes = models.CharField(max_length=500)
    taskdatecomplete = models.DateField(("Date"), default=datetime.date.today)
    taskdatestart = models.DateField(("Date"), default=datetime.date.today)
    taskcomplete = models.BooleanField(default=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    invoicesent = models.BooleanField(default=False)
    client = models.CharField(max_length=25)

    def __str__(self):
        return self.addressnumber + self.addressstreet + self.quickdescrip + self.lockboxcode + self.client

    def get_absolute_url(self):
        return reverse('wordorderapp:detail', kwargs={'pk': self.pk})

class Dailyjournal(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    journaldate = models.DateField(("Date"), default=datetime.date.today)
    description = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('wordorderapp:home1')

wordorderapp/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

wordorderapp/views.py
from django.views import generic
from django.contrib.auth import authenticate
from .models import Workorder
from .models import Dailyjournal
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.views.generic import View
from .forms import UserForm
from django.utils.http import is_safe_url
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login, logout as auth_logout
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, RedirectView
from django.urls import reverse
from django.views.generic import TemplateView


class HomePage1View(TemplateView):

    template_name = 'wordorderapp/homepage1.html'

class IndexView(generic.ListView):
    template_name = 'wordorderapp/index.html'
    paginate_by = 20
    def get_queryset(self):
        return Workorder.objects.filter(user=self.request.user)

    context_object_name = 'index'

class IndexView1(generic.ListView):
    template_name = 'wordorderapp/index1.html'
    paginate_by = 20
    def get_queryset(self):
        return Workorder.objects.all()

    context_object_name = 'index1'

class IndexView2(generic.ListView):
    template_name = 'wordorderapp/index2.html'
    paginate_by = 20
    def get_queryset(self):
        return Workorder.objects.all()

    context_object_name = 'index2'

class DetailView(generic.DetailView):
    model = Workorder
    context_object_name = 'detail'
    template_name = 'wordorderapp/detail.html'

class WorkCreate(CreateView):
    model = Workorder
    fields = ['addressnumber', 'addressstreet', 'addresstown', 'addressstate', 'quickdescrip', 'lockboxcode', 'description', 'proposalorestimatenumber', 'clientemailinfo', 'techniciancompletionnotes', 'taskdatecomplete', 'taskdatestart', 'taskcomplete', 'user', 'invoicesent', 'client']

class WorkUpdate(UpdateView):
    model = Workorder
    fields = ['techniciancompletionnotes', 'taskdatecomplete', 'taskdatestart', 'taskcomplete']
    template_name = 'wordorderapp/workorder_update_form.html'

class WorkUpdate1(UpdateView):
    model = Workorder
    fields = ['invoicesent']
    template_name = 'wordorderapp/workorder_update_form1.html'

class WorkUpdateAdmin(UpdateView):
    model = Workorder
    fields = ['addressnumber', 'addressstreet', 'addresstown', 'addressstate', 'quickdescrip', 'lockboxcode', 'description', 'proposalorestimatenumber', 'clientemailinfo', 'techniciancompletionnotes', 'taskdatecomplete', 'taskdatestart', 'taskcomplete', 'user', 'invoicesent', 'client']
    template_name = 'wordorderapp/workorder_update_formadmin.html'

class WorkDelete(DeleteView):
    model = Workorder
    success_url = reverse_lazy('wordorderapp:index')


class DailyCreate(CreateView):
    model = Dailyjournal
    fields = ['user', 'journaldate', 'description']



class UserFormView(View):
    form_class = UserForm
    template_name = 'wordorderapp/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})
    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)


            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns User Objects if credentials are correct

            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    auth_login(request, user)
                    return redirect('wordorderapp:loginsuccess')

        return render(request, self.template_name, {'form': form})

class LoginView(FormView):
    """
    Provides the ability to login as a user with a username and password
    """
    success_url = 'wordorderapp:loginsuccess'
    form_class = AuthenticationForm
    template_name = 'wordorderapp/login_form.html'
    redirect_field_name = REDIRECT_FIELD_NAME

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        auth_login(self.request, form.get_user())

        # If the test cookie worked, go ahead and
        # delete it since its no longer needed
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()

        return super(LoginView, self).form_valid(form)

    def get_success_url(self):
        redirect_to = self.request.GET.get(self.redirect_field_name)
        if not is_safe_url(url=redirect_to, allowed_hosts=self.request.get_host()):
            redirect_to = reverse(self.success_url)
        return redirect_to

class LogoutView(RedirectView):
    """
    Provides users the ability to logout
    """

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return redirect('wordorderapp:logoutsuccess')
        # return super(LogoutView, self).get(request, *args, **kwargs)

class WorkOrderSearchView(generic.ListView):
    template_name = 'workorder_list.html'
    model = Workorder

    def get_queryset(self):
        try:
            addressstreet = self.kwargs['addressstreet']
        except:
            addressstreet = ''
        if (addressstreet != ''):
            object_list = self.model.objects.filter(addressstreet__icontains = addressstreet)
        else:
            object_list = self.model.objects.all()
        return object_list

class LoginSuccessView(TemplateView):

    template_name = 'wordorderapp/successpage.html'

class LogoutSuccessView(TemplateView):

    template_name = 'wordorderapp/logoutsuccesspage.html'

wordorderapp/templates/wordorderapp/basehomepage.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'wordorderapp/style.css' %}">
  </head>
  <body>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
  <div class="container-fluid">
  <a class="navbar-brand" href="{% url 'home' %}">AMI Property Services</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'wordorderapp:home1' %}">Work Order System <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'wordorderapp:login' %}">Log In</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'wordorderapp:logout' %}">Log Out</a>
      </li>
    </ul>
  </div>
  </div>
</nav>



{% block body %}
{% endblock %}


<footer>
<nav class="navbar-wrapper navbar-inverse">
<div class="container-fluid padding">
<div class="row text-center">

</div>
</div>
</nav>
</footer>

</html>

wordorderapp/templates/wordorderapp/homepage.html
{% extends 'wordorderapp/basehomepage.html' %}


{% block body %}

<div class="container-2">
    <div class="box-01"><h2>Welcome to the Home Page</h2></div>
</div>

<div class="container-2">
<div class="box-01">
        <a href="{% url 'wordorderapp:login' %}"><h3>Log in to Access Work Order Site</h3></a>
</div>
</div>
{% if user.is_authenticated %}

<div class="container-1">
    <div class="box-01">
        <a href="{% url 'wordorderapp:index' %}"><h3>Go to my work orders</h3></a>
    </div>
</div>

{% endif %}

{% endblock %}

wordorderapp/templates/wordorderapp/homepage1.html
{% extends 'wordorderapp/base.html' %}


{% block body %}

{% if user.is_authenticated %}
<div class="container-2">
    <div class="box-1"><h2>Welcome to the Home Page</h2></div>
</div>

<div class="container-1">
    <div class="box-1">
        <a href="{% url 'wordorderapp:index' %}"><h3>Go to my work orders</h3></a>
    </div>

</div>
<div class="container-1">
    <div class="box-2">
        <a href="https://docs.google.com/spreadsheets/d/1Wr9eAgGghuWDC090Zw3I3WiSgdfI75h_eivY15AbIqM/edit?usp=sharing"><h3>Lawn Spreadsheet</h3></a>
    </div>
</div>

<div class="container-1">
    <div class="box-3">
        <a href="www.google.com"><h3>Employee Handbook</h3></a>
    </div>
</div>
{% endif %}

{% endblock %}

wordorderapp/templates/wordorderapp/index.html
{% extends 'wordorderapp/base.html' %}

{% block body %}

<h2>My Uncompleted Work Orders</h2>


<table class="table table-bordered">
  <thead>
    <tr>
      <th>Address Number</th>
      <th>Street</th>
      <th>Town</th>
      <th>State</th>
      <th>LockBox</th>
      <th>Task Assigned Date</th>
      <th>Client</th>
      <th>Work Order Details</th>
      <th>Update Status Completion</th>
    </tr>
  </thead>
  <tbody>
      {% for object in object_list %}
          {% if object.taskcomplete is False %}
              <tr>
                <td>{{ object.addressnumber }}</td>
                <td>{{ object.addressstreet }}</td>
                <td>{{ object.addresstown }}</td>
                <td>{{ object.addressstate }}</td>
                <td>{{ object.lockboxcode }}</td>
                <td>{{ object.taskdatestart }}</td>
                <td>{{ object.client }}</td>
                <td> <a href="{% url 'wordorderapp:detail' object.id %}"> Work Order Information </a></td>
                <td> <a href="{% url 'wordorderapp:updatework' object.id %}"> Work Order Information </a></td>
              </tr>
              {% endif %}
          {% endfor %}
  </tbody>
</table>

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}

wordorderapp/templates/wordorderapp/index1.html
{% extends 'wordorderapp/base.html' %}

{% block body %}

<h2>Open Invoices Not Sent</h2>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Address Number</th>
      <th>Street</th>
      <th>Town</th>
      <th>State</th>
      <th>LockBox</th>
      <th>Task Completion Date</th>
      <th>Client</th>
      <th>Work Order Details</th>
      <th>Change Sent Status</th>
    </tr>
  </thead>
  <tbody>
  {% for object in object_list %}
    {% if object.invoicesent is False %}
      <tr>
        <td>{{ object.addressnumber }}</td>
        <td>{{ object.addressstreet }}</td>
        <td>{{ object.addresstown }}</td>
        <td>{{ object.addressstate }}</td>
        <td>{{ object.lockboxcode }}</td>
        <td>{{ object.taskdatecomplete }}</td>
        <td>{{ object.client }}</td>
        <td> <a href="{% url 'wordorderapp:detail' object.id %}"> Work Order Information </a></td>
        <td> <a href="{% url 'wordorderapp:updatework1' object.id %}"> Work Order Information </a></td>
      </tr>
    {% endif %}
  {% endfor %}
  </tbody>
</table>

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}

wordorderapp/templates/wordorderapp/index2.html
{% extends 'wordorderapp/base.html' %}

{% block body %}

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Address Number</th>
      <th>Street</th>
      <th>Town</th>
      <th>State</th>
      <th>LockBox</th>
      <th>Task Assigned Date</th>
      <th>Client</th>
      <th>Work Order Details</th>
    </tr>
  </thead>
  <tbody>
  {% for object in object_list %}
    {% if object.taskcomplete is True %}
      <tr>
        <td>{{ object.addressnumber }}</td>
        <td>{{ object.addressstreet }}</td>
        <td>{{ object.addresstown }}</td>
        <td>{{ object.addressstate }}</td>
        <td>{{ object.lockboxcode }}</td>
        <td>{{ object.taskdatestart }}</td>
        <td>{{ object.client }}</td>
        <td> <a href="{% url 'wordorderapp:detail' object.id %}"> Work Order Information </a></td>
      </tr>
    {% endif %}
  {% endfor %}
  </tbody>
</table>

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}

wordorderapp/templates/wordorderapp/index3.html
{% extends 'wordorderapp/base.html' %}


{% block body %}


{% for object in object_list %}

{{ object.addressnumber }} {{ object.addressstreet }} <a href="{% url 'wordorderapp:detail' object.id %}"> Work Order Information </a>

{% endfor %}

{% endblock %}

wordorderapp/templates/wordorderapp/login_form.html
{% extends 'wordorderapp/base.html' %}
{% block title %}Log In{% endblock %}

{% block body %}
<form class="form-horizontal" action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" enctype="multipart/form-data" />
</form>

                    <a href="{% url 'wordorderapp:register' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Create Account
                    </a>
{% endblock %}

wordorderapp/templates/wordorderapp/logout_form.html
{% extends 'wordorderapp/base.html' %}
{% block title %}Log Out{% endblock %}


{% block body %}
<form class="form-horizontal" action="" method="get">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="" enctype="multipart/form-data" />
</form>

{% endblock %}

wordorderapp/templates/wordorderapp/logoutsuccesspage.html
{% extends 'wordorderapp/basehomepage.html' %}


{% block body %}

<div class="container-2">
    <div class="box-0"><h2>You have successfully logged out!</h2></div>
</div>

<div class="box-1">
        <a href="{% url 'wordorderapp:login' %}"><h3>Log in to Access Work Order Site</h3></a>
</div>


{% endblock %}

wordorderapp/templates/wordorderapp/successpage.html
{% extends 'wordorderapp/base.html' %}


{% block body %}



{% if user.is_authenticated %}
<div class="container-2">
    <div class="box-1"><h2>Congrats you are logged in!</h2></div>
</div>

<div class="container-1">
    <div class="box-1">
        <a href="{% url 'wordorderapp:index' %}"><h3>Go to my work orders</h3></a>
    </div>

</div>
<div class="container-1">
    <div class="box-2">
        <a href="https://docs.google.com/spreadsheets/d/1Wr9eAgGghuWDC090Zw3I3WiSgdfI75h_eivY15AbIqM/edit?usp=sharing"><h3>Lawn Spreadsheet</h3></a>
    </div>
</div>

<div class="container-1">
    <div class="box-3">
        <a href="www.google.com"><h3>Employee Handbook</h3></a>
    </div>
</div>
{% endif %}

{% endblock %}

wordorderapp/templates/wordorderapp/workorder_form.html
{% extends 'wordorderapp/base.html' %}
{% block title %}Add a New Monthly Task{% endblock %}
{% block months_active %}active{% endblock %}
{% block body %}
<h1>Create Work Order</h1>
<h2></h2>
<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

        <input type="submit" value="Save"/>
</form>

{% endblock %}

wordorderapp/templates/wordorderapp/workorder_list.html
{% extends 'wordorderapp/base.html' %}


{% block body %}



<form method='GET'>
  <input type='text' name='q' value='{{ request.GET.q }}'>
  <input class="button" type='submit' value="Search Profile">
</form>

{% for object in object_list %}
<ul>
{{ object.addressnumber }} {{ object.addressstreet }} <a href="{% url 'wordorderapp:detail' object.id %}"> Work Order Information </a>
</ul>
{% endfor %}
{% endblock %}

wordorderapp/templates/wordorderapp/workorder_update_form.html
{% extends 'wordorderapp/base.html' %}

{% block body %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

{% endblock %}